name: dj-cleiton-rasta
version: 0.1.0.0
github: "celsobonutti/dj-cleiton-rasta"
license: BSD3
author: "Celso Bonutti"
maintainer: "i.am@cel.so"
copyright: "2021 Celso Bonutti"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/dj-cleiton-rasta#readme>

dependencies:
  - base >= 4.17.0.0 && < 5
  - discord-haskell == 1.15.3 && < 2.0
  - text >= 2.0.1 && < 2.1
  - unliftio >= 0.2.20 && < 0.3
  - megaparsec >= 9.1.0 && < 10
  - parser-combinators >= 1.3.0 && < 1.4.0
  - containers >= 0.6.7 && < 0.7
  - req >= 3.9.1 && < 4
  - aeson >= 2.1.1.0 && < 3.0
  - data-default >= 0.7.1.1 && < 0.8
  - mtl >= 2.2.2 && < 2.3

library:
  source-dirs: src

executables:
  dj-cleiton-rasta-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dj-cleiton-rasta

tests:
  dj-cleiton-rasta-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dj-cleiton-rasta

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - OverloadedRecordDot
  - DuplicateRecordFields
