name:                dj-cleiton-rasta
version:             0.1.0.0
github:              "celsobonutti/dj-cleiton-rasta"
license:             BSD3
author:              "Celso Bonutti"
maintainer:          "i.am@cel.so"
copyright:           "2021 Celso Bonutti"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/dj-cleiton-rasta#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell == 1.8.8 && < 2.0
- ffmpeg-light == 0.14.0 && < 0.15
- text >= 1.2.0.0 && < 2.0
- protolude >= 0.3.0 && < 0.4
- unliftio >= 0.2.20 && < 0.3
- turtle >= 1.5.22 && < 2
- megaparsec >= 9.1.0 && < 10
- parser-combinators >= 1.3.0 && < 1.4.0
- containers >= 0.6.5.1 && < 0.7
- req >= 3.9.1 && < 4
- aeson >= 1.5 && < 1.6

library:
  source-dirs: src

executables:
  dj-cleiton-rasta-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dj-cleiton-rasta

tests:
  dj-cleiton-rasta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dj-cleiton-rasta

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NamedFieldPuns
  - DuplicateRecordFields
