name: dj-cleiton-rasta
version: 0.1.0.0
github: "celsobonutti/dj-cleiton-rasta"
license: BSD3
author: "Celso Bonutti"
maintainer: "i.am@cel.so"
copyright: "2021 Celso Bonutti"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/dj-cleiton-rasta#readme>

pkg-config-dependencies:
  - libsodium >= 1.0.13

dependencies:
  - base >= 4.16.0.0 && < 5
  - discord-haskell >= 1.13.0 && < 1.14
  - discord-haskell-voice >= 2.3.1 && < 2.4
  - text >= 1.2.5.0 && < 2.0
  - unliftio >= 0.2.20 && < 0.3
  - megaparsec >= 9.1.0 && < 10
  - parser-combinators >= 1.3.0 && < 1.4.0
  - containers >= 0.6.5.1 && < 0.7
  - req >= 3.9.1 && < 4
  - aeson >= 2.0.3.0 && < 3.0
  - data-default >= 0.7.1.1 && < 0.8
  - mtl >= 2.2.2 && < 2.3

library:
  source-dirs: src

executables:
  dj-cleiton-rasta-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dj-cleiton-rasta

tests:
  dj-cleiton-rasta-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dj-cleiton-rasta

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - OverloadedRecordDot
  - DuplicateRecordFields
